version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:

### Workspace Utilities ##################################
  workspace:
    build: ./workspace
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${DATA_PATH_HOST}/pbf:${APP_CODE_PATH_CONTAINER}/pbf
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    tty: true
    networks:
      - frontend
      - backend

### Katotherian ##################################
  kartotherian:
    build: ./kartotherian
    ports:
      - "6533:6533"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KARTOTHERIAN_NPM_LINK=${KARTOTHERIAN_NPM_LINK}
      - KARTOTHERIAN_NPM_TEST=${KARTOTHERIAN_NPM_TEST}
      - KARTOTHERIAN_NPM_START=${KARTOTHERIAN_NPM_START}
      - KARTOTHERIAN_LINK_PATH=${KARTOTHERIAN_LINK_PATH}
      - KARTOTHERIAN_SKIP_LINK_PATH=${KARTOTHERIAN_SKIP_LINK_PATH}
    depends_on:
      - workspace
      - postgres-postgis
      - cassandra
      - redis
    volumes:
      - ${APP_CODE_PATH_HOST}/kartotherian:/home/kartotherian
      - ${APP_CODE_PATH_HOST}/dependencies:${KARTOTHERIAN_LINK_PATH}
    tty: true
    networks:
      - frontend
      - backend    

### PostgreSQL PostGis ##################################
  postgres-postgis:
    build: ./postgres-postgis
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${DATA_PATH_HOST}/pbf:/home/pbf
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend    

### Mapbox Studio Classic ##################################
  mapbox-studio-classic:
    build: ./mapbox-studio-classic
    volumes: 
      - ${APP_CODE_PATH_HOST}:/root/source
      - ${DATA_PATH_HOST}/.mapbox-studio:/root/.mapbox-studio
    ports:
      - "3000:3000"
    depends_on:
      - workspace
      - postgres-postgis
    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    networks:
      - frontend
      - backend 

### Cassandra ##################################
  cassandra: 
    build: ./cassandra
    volumes:
      - ${DATA_PATH_HOST}/cassandra:/var/lib/cassandra
    ports:
      - "${CASSANDRA_PORT}:9042"
    networks:
      - backend    

### Redis ##################################
  redis:
    build: ./redis
    volumes:
        - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend 

### Kosmtik ##################################
  kosmtik:
    build: ./kosmtik
    volumes:
      - ../osm-bright.tm2:/opt/project
      - ../osm-bright.tm2source:/opt/project/src
    ports:
      - "6789:6789"
    environment:
      - USER_ID=1000
    depends_on:
      - workspace
      - postgres-postgis
    tty: true
    networks:
      - frontend
      - backend 