version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:

### Workspace Utilities ##################################
  workspace:
    build:
      context: ./
      dockerfile: workspace/Dockerfile
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - WORKSPACE_NCPU=${WORKSPACE_NCPU}
      - WORKSPACE_MEMORY=${WORKSPACE_MEMORY}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${DATA_PATH_HOST}/pbf:${APP_CODE_PATH_CONTAINER}/pbf
      - ./common/mapping.yml:/etc/imposm/mapping.yml

    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    networks:
      - frontend
      - backend

### Katotherian ##################################
  kartotherian:
    build: ./kartotherian
    ports:
      - "6533:6533"
      - "16534:16534"
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=5432
      - PGHOST=postgres-postgis
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    depends_on:
      - workspace
      - postgres-postgis
      - cassandra
      - redis
      - tegola
    volumes:
      - ${APP_CODE_PATH_HOST}/kartotherian:/home/kartotherian
      - ${APP_CODE_PATH_HOST}/dependencies:/srv/dependencies
      - ${APP_CODE_PATH_HOST}/imposm/expiretiles:/srv/expiretiles
    tty: true
    networks:
      - frontend
      - backend

### PostgreSQL PostGis ##################################
  postgres-postgis:
    image: postgis/postgis:11-3.1
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "${PGPORT:-5432}:5432"
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    depends_on:
      - workspace
    networks:
      - backend

  ### Cassandra ##################################
  cassandra:
    image: cassandra:3.11.4  # Production version
    volumes:
      - ${DATA_PATH_HOST}/cassandra:/var/lib/cassandra
    ports:
      - "${CASSANDRA_PORT:-9042}:9042"
    networks:
      - backend

### Redis ##################################
  redis:
    image: redis:latest
    volumes:
        - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - backend

### Graphite statsd ##################################
  statsd:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "8000:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125"
      - "8126:8126"
    restart: always
    networks:
      - backend

### Tegola ##################################
  tegola:
    build: https://github.com/go-spatial/tegola.git#v0.14.x
    volumes:
      - ./tegola/tegola.toml:/etc/tegola.toml
    ports:
      - "${TEGOLA_PORT:-8080}:8080"
    networks:
      - backend
    command: serve --config /etc/tegola.toml

### Maputnik ##################################
  maputnik:
    image: maputnik/editor:latest
    ports:
      - "${MAPUTNIK_PORT:-8888}:8888"
    networks:
      - frontend
      - backend

  osmosis:
    build:
      context: ./smoketests
      dockerfile: build.Dockerfile
    volumes:
      - ${DATA_PATH_HOST}/pbf:/etc/pbf

  test:
    build:
      context: ./
      dockerfile: smoketests/test.Dockerfile
    environment:
      - PGDATABASE=${PGDATABASE:-gis}
      - PGUSER=${PGUSER:-default}
      - PGPASSWORD=${PGPASSWORD:-secret}
      - POSTGRES_DB=${PGDATABASE:-gis}
      - POSTGRES_USER=${PGUSER:-default}
      - POSTGRES_PASSWORD=${PGPASSWORD:-secret}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${APP_CODE_PATH_HOST:-..}/kartodock:/etc/kartodock
