version: '3'
services:
  postgres-postgis:
    build: ./postgres-osm
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${DATA_PATH_HOST}/pbf:/home/pbf
      - ../osm-bright.tm2source:/home/src
    ports:
      - "${POSTGRES_PORT}:5432"
    network_mode: "host"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  mapbox-studio-classic:
    image: stepankuzmin/mapbox-studio-classic
    volumes: 
      - ~/wikimedia-workspace/mapstack:/root
      - ../data/.mapbox-studio:/root/.mapbox-studio
    ports:
      - "3000:3000"
    network_mode: "host"
  cassandra: 
    image: spotify/cassandra
    ports:
      - "9042:9042"
    network_mode: "host"
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: "host"
  # kosmtik:
  #   build: ./kosmtik
  #   volumes:
  #     - ../osm-bright.tm2:/opt/project
  #     - ../osm-bright.tm2source:/opt/project/src
  #   network_mode: "host"
  #   ports:
  #     - "6789:6789"
  #   environment:
  #     - USER_ID=1000
  #   tty: true